### ISSUE TITLE
Add support for all endpoints

### ISSUE THREAD

**Issue by Jackenmen** [Jackenmen/rlapi#3]
- [x] Population
    - [x] `GET /population` (#98)
- [x] Leaderboard
    - [x] `GET /leaderboard/skill/{Platform}/{Playlist}` (#99)
    - [x] `GET /leaderboard/stat/{Platform}/{Stat}` (#99)
- [x] Player
    - [x] `GET /player/titles/{Platform}/{PlayerID}` (#100)
    - [x] `GET /player/skill/{Platform}/{PlayerID}`
    - [x] `GET /player/stat/{Platform}/{PlayerID}` (#97)
